"""add reviews to pois

Revision ID: 23e8c4b0eaed
Revises: ffec9c372e4b
Create Date: 2026-01-05 15:01:13.468877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e8c4b0eaed'
down_revision: Union[str, None] = 'ffec9c372e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('reviews', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'reviews')
    # ### end Alembic commands ###
