"""add structured_preferences to trips

Revision ID: ffec9c372e4b
Revises: 006_add_poi_metadata
Create Date: 2026-01-05 14:56:30.991739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffec9c372e4b'
down_revision: Union[str, None] = '006_add_poi_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guest_devices_device_id_key', 'guest_devices', type_='unique')
    op.drop_index('ix_guest_devices_device_id', table_name='guest_devices')
    op.create_index(op.f('ix_guest_devices_device_id'), 'guest_devices', ['device_id'], unique=True)
    op.add_column('trips', sa.Column('structured_preferences', sa.JSON(), nullable=True))
    op.drop_constraint('fk_trips_user_id', 'trips', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_trips_user_id', 'trips', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trips', 'structured_preferences')
    op.drop_index(op.f('ix_guest_devices_device_id'), table_name='guest_devices')
    op.create_index('ix_guest_devices_device_id', 'guest_devices', ['device_id'], unique=False)
    op.create_unique_constraint('guest_devices_device_id_key', 'guest_devices', ['device_id'])
    # ### end Alembic commands ###
