"""
Critique API endpoints for trip validation.
"""
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from src.infrastructure.database import get_db
from src.infrastructure.models import TripModel
from src.application.trip_planner import TripPlannerOrchestrator
from src.domain.schemas import CritiqueResponse
from src.auth.dependencies import (
    get_auth_context,
    AuthContext,
    check_trip_ownership,
)


router = APIRouter(prefix="/trips", tags=["critique"])


@router.get(
    "/{trip_id}/critique",
    response_model=CritiqueResponse,
    summary="Get trip critique",
    description="Fetch validation issues and warnings for a trip itinerary."
)
async def get_trip_critique(
    trip_id: UUID,
    db: AsyncSession = Depends(get_db),
    auth: AuthContext = Depends(get_auth_context),
) -> CritiqueResponse:
    """
    Get stored critique for a trip.

    Returns the validation issues and warnings generated by the Trip Critic.
    The critique includes:
    - Daily load checks (too busy for pace)
    - Meal coverage (missing breakfast/lunch/dinner)
    - Time consistency (overlaps, invalid ranges)
    - Travel fatigue (long distances between activities)
    - Nightlife vs sleep schedule conflicts
    - Consecutive intense days warnings

    Args:
        trip_id: UUID of the trip

    Returns:
        CritiqueResponse with list of issues, counts by severity, and summary

    Raises:
        HTTPException 404 if trip not found
    """
    result = await db.execute(
        select(TripModel).where(TripModel.id == trip_id)
    )
    trip = result.scalar_one_or_none()

    if not trip:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Trip with ID {trip_id} not found"
        )

    if not check_trip_ownership(trip, auth):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="You don't have access to this trip"
        )

    orchestrator = TripPlannerOrchestrator()

    try:
        critique = await orchestrator.get_critique(trip_id, db)
        return critique

    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(e)
        )

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected error: {str(e)}"
        )
